# GitHub Actions Basics
#
# Copyleft (c) Armen Barsegyan 2019
#
name: MyFirstGitHubAction

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
  my-testing:
    runs-on: ubuntu-latest
    
